### ISSUE TITLE
`todo-list` app Undo does not behave as expected

### ISSUE THREAD

**Issue by scott-maddox** [enthought/ets-examples#16]
In the `todo-list` app, Undo'ing new task creations does not behave as expected. In particular, creating a few new tasks, then undo'ing the creations, then creating one new task results in all of the tasks reappearing.

To reproduce:
1. Start the app: `cd todo-list` and `python -m todo_list.app`.
2. Press `New Task` three times to create three new empty tasks.
3. Press `Edit > Undo` three times to undo the task creation.
4. Press `New Task` once.

Expected Result: There should one empty task visible.
Actual Result: There are four empty tasks visible.

**Comment by corranwebster** [comment]
Yes - this is related to the issues you were seeing in #15.  I have a resolution to this but don't want to include it in the basic example as it complicates things.

I have resolved this by removing undo/redo.
